### ISSUE TITLE
Don't hoard high paying TXs

### ISSUE THREAD

**Issue by 1ma** [polespinasa/bitcoin-grouphug#3]
If the backend receives several transactions paying enough fees to be broadcasted it should broadcast a batch even if they pay very different fees one from the other.

## Example

High prio fees are at 1 s/vB

Tx1: 30 s/vB
Tx2: 500 s/vB
Tx3: 100 s/vB

### Current behavior

The backend creates 3 different groups and waits for more TXs to come in.

### Desired behavior

The backend should batch the transactions and broadcast them because fees to be included in the next block are at 1 s/vB.

**Comment by polespinasa** [comment]
ACK, will implement it.

But I don't think they should be batched but just close and broadcast the groups at the current state. Batching them would have no effect, and at some point the tx with more fee rate could think that are being "stolen"?

**Comment by polespinasa** [comment]
A first solution is implemented in the following commit https://github.com/polespinasa/bitcoin-grouphug/commit/d4c9c15c1d47c58e6b98898e9c3ac1371e2b7842
